### ISSUE TITLE
For Trained  .pth

### ISSUE THREAD

**Issue by ABexit** [NickLucche/lane-detection#1]
Hello, Thanks for your sharing & Then, can you share the trained .pth files?
Any way, Thanks a lot : )

**Comment by NickLucche** [comment]
Hi @ABexit, sorry for the delayed answer but I must've missed the github notification.

In case you're still interested, I can provide the final trained model as a download from GDrive.
Let me know, sorry again!

**Comment by ABexit** [comment]
> Hi @ABexit, sorry for the delayed answer but I must've missed the github notification.
> 
> In case you're still interested, I can provide the final trained model as a download from GDrive.
> Let me know, sorry again!

You are so kind, Bro. Thx for your replay.Yes, I'm interested in it, there are little confuse from the codes,I wonder have a demo try. Thx again for your sharing & replay.

**Comment by NickLucche** [comment]
Okay I updated the README so that you can download and (hopefully) make use of the pre-trained model. Have fun!

**Comment by NickLucche** [comment]
Feel free to open new tickets if you face other issues :)

**Comment by ABexit** [comment]
> Okay I updated the README so that you can download and (hopefully) make use of the pre-trained model. Have fun!

Okay, Thx a lot. Best wishes to you.
