### ISSUE TITLE
Markings cannot be annoted at the correct place in the image.

### ISSUE THREAD

**Issue by zouzhenhong98** [NickLucche/lane-detection#3]
I tried my own video while running video-comparison.py, when I found the detected lanes were not added at the correct place on in the image. Do you know how to fix it?

It seems that you are trying to import hough_transform.py to fix the problem. But you only import it, not utilizing any function of it in the video-comparison.py.

**Comment by NickLucche** [comment]
No actually the `hough_transform` import is leftover from some experiments I was trying to do to compare results, apologies.

Running you're own custom video through the net is unluckily not the easiest task, as I tried too.
First of all, keep in mind that the weights I provided are from some under-trained model as I tried to explain in the README; most importantly, my take on the mistakes the model makes on 'custom' videos is that you're forcing some sort of implicit bias regarding viewpoint of the camera and corresponding positioning of lanes by training on the dataset I used without any kind of data-augmentation to enforce the fact that camera position might not always be the same.

Therefore, it's not as nearly as robust as it should for real-world uses.
