### ISSUE TITLE
 visual_evaluation.py have some error

### ISSUE THREAD

**Issue by NeilKuo** [NickLucche/lane-detection#5]
Hi,I have some questions.
I run  visual_evaluation.py and the following error occurred.
> python visual_evaluation.py 
Using device: GeForce RTX 2080 Ti
Loading stored model
Instantiating Segnet encoder with max unpooling
Model loaded
Traceback (most recent call last):
  File "visual_evaluation.py", line 36, in <module>
    output = model(frames)
  File "/home/steam/anaconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/steam/lane-detection/segnet_conv_lstm_model.py", line 84, in forward
    output, _ = self.lstm(batched_code_sequence)
  File "/home/steam/anaconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/steam/lane-detection/lstm/convlstm.py", line 136, in forward
    cur_state=[h, c])
  File "/home/steam/anaconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/steam/lane-detection/lstm/convlstm.py", line 45, in forward
    combined = torch.cat([input_tensor, h_cur], dim=1)  # concatenate along channel axis
RuntimeError: Expected object of backend CUDA but got backend CPU for sequence element 0 in sequence argument at position #1 'tensors'

tks!!

**Comment by NickLucche** [comment]
Hey, thanks for taking your time to open an issue.
I'll try to run the project with a different configuration and I'll get back to you asap!

**Comment by NickLucche** [comment]
Hi again, I updated the code so that you should be able to run tests on GPUs too, you can also pass the model filepath with the `-m` option.
Let me know!

**Comment by NeilKuo** [comment]
Hi
Thank you for your help.
I am writing to enquire about I run the video-comparison.py have same error.
The error is as follows
`python video-comparison.py --full-video-size True --filename 1113.MP4 -m ./model.torch
Using device: GeForce RTX 2080 Ti
Instantiating Segnet encoder with max unpooling
Loading model..
Using images at original scale
OpenCV: FFMPEG: format mp4 / MP4 (MPEG-4 Part 14)
fourcc tag 0x7634706d/'mp4v' codec_id 000C
fourcc tag 0x31637661/'avc1' codec_id 001B
fourcc tag 0x33637661/'avc3' codec_id 001B
fourcc tag 0x31766568/'hev1' codec_id 00AD
fourcc tag 0x31637668/'hvc1' codec_id 00AD
fourcc tag 0x7634706d/'mp4v' codec_id 0002
fourcc tag 0x7634706d/'mp4v' codec_id 0001
fourcc tag 0x7634706d/'mp4v' codec_id 0007
fourcc tag 0x7634706d/'mp4v' codec_id 003D
fourcc tag 0x7634706d/'mp4v' codec_id 0058
fourcc tag 0x312d6376/'vc-1' codec_id 0046
fourcc tag 0x63617264/'drac' codec_id 0074
fourcc tag 0x7634706d/'mp4v' codec_id 00A3
fourcc tag 0x39307076/'vp09' codec_id 00A7
fourcc tag 0x31307661/'av01' codec_id 801D
fourcc tag 0x6134706d/'mp4a' codec_id 15002
fourcc tag 0x6134706d/'mp4a' codec_id 1502D
fourcc tag 0x6134706d/'mp4a' codec_id 15001
fourcc tag 0x6134706d/'mp4a' codec_id 15000
fourcc tag 0x332d6361/'ac-3' codec_id 15003
fourcc tag 0x332d6365/'ec-3' codec_id 15028
fourcc tag 0x6134706d/'mp4a' codec_id 15004
fourcc tag 0x61706c6d/'mlpa' codec_id 1502C
fourcc tag 0x43614c66/'fLaC' codec_id 1500C
fourcc tag 0x7375704f/'Opus' codec_id 1503C
fourcc tag 0x6134706d/'mp4a' codec_id 15005
fourcc tag 0x6134706d/'mp4a' codec_id 15018
fourcc tag 0x6134706d/'mp4a' codec_id 15803
fourcc tag 0x7334706d/'mp4s' codec_id 17000
fourcc tag 0x67337874/'tx3g' codec_id 17005
fourcc tag 0x646d7067/'gpmd' codec_id 18807
fourcc tag 0x316d686d/'mhm1' codec_id 15817
Traceback (most recent call last):
  File "video-comparison.py", line 74, in <module>
    marks = model(inputs)
  File "/home/steam/anaconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/steam/lane-detection/segnet_conv_lstm_model.py", line 84, in forward
    output, _ = self.lstm(batched_code_sequence)
  File "/home/steam/anaconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/steam/lane-detection/lstm/convlstm.py", line 136, in forward
    cur_state=[h, c])
  File "/home/steam/anaconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/steam/lane-detection/lstm/convlstm.py", line 45, in forward
    combined = torch.cat([input_tensor, h_cur], dim=1)  # concatenate along channel axis
RuntimeError: Expected object of backend CUDA but got backend CPU for sequence element 0 in sequence argument at position #1 'tensors'`
I am a graduate school student.
My research interests is using Deep Neural network to lane detection.
Your reply is so important  to me.
Thank you so much.

**Comment by NickLucche** [comment]
Hey,
my bad for not documenting the code more clearly, I used to run `video-comparison.py` using my laptop with no integrated GPU. 
I'll add support for GPUs asap, meanwhile you can run the code using your CPU instead if you wish, by changing line 42 of the script with:
`tu.load_model_checkpoint(model, args.model_path, inference=False,
                         map_location=torch.device("cpu"))`

or by either running the script and 'masking' the GPU by setting the env variable using:
`export CUDA_VISIBLE_DEVICES=""`

**Comment by NickLucche** [comment]
I added support for creating a video sample running the model on GPU, let me know.
I tested using `python3 video-comparison.py -m model-fixed.torch --full-video-size`.
